# Primeira Seção: Transparência e Acesso à Informação

No Tribunal Regional Eleitoral de Roraima (TRERR), acreditamos firmemente que a transparência é a pedra angular da confiança pública e da governança eficaz. Nossa dedicação ao acesso à informação reflete nosso compromisso em promover a abertura e a responsabilidade. Esta seção é projetada para oferecer a você, nosso público, uma visão abrangente de como estamos estruturando nossos esforços para alcançar nossos objetivos institucionais, garantindo ao mesmo tempo a eficiência e a eficácia de nossa gestão. Desde o planejamento estratégico até a execução de nossas responsabilidades e competências, cada elemento aqui apresentado destaca nossa jornada em direção a uma administração pública transparente e responsável.

## 1. Planejamento Estratégico Institucional

Publicamos nosso Planejamento Estratégico Institucional, destacando nossos objetivos estratégicos, metas e indicadores de desempenho.

[Consulte o Planejamento Estratégico Institucional](00.diversos/pagina.em.construcao.qmd)  
<!-- Endereço original: 01.gestao/01.planejamento.estrategico.qmd -->

## 2. Resultados do Planejamento Estratégico

Acompanhe os resultados alcançados pelo TRERR em relação ao Planejamento Estratégico Institucional.

[Veja os Resultados do Planejamento Estratégico](00.diversos/pagina.em.construcao.qmd)  
<!-- Endereço original: 01.gestao/02.resultados.planejamento.qmd -->

## 3. Competências e Responsabilidades

Informações sobre as competências e responsabilidades do TRERR.

[Conheça as Competências e Responsabilidades](00.diversos/pagina.em.construcao.qmd)  
<!-- Endereço original: 01.gestao/03.competencias.responsabilidades.qmd -->

## 4. Estrutura Organizacional

Nossa estrutura organizacional é apresentada, mostrando a relação hierárquica entre as unidades.

[Visualize a Estrutura Organizacional](00.diversos/pagina.em.construcao.qmd)  
<!-- Endereço original: 01.gestao/04.estrutura.organizacional.qmd -->

## 5. Atos Normativos

Acesse os atos normativos expedidos pelo TRERR.

[Consulte os Atos Normativos](00.diversos/pagina.em.construcao.qmd)  
<!-- Endereço original: 01.gestao/05.atos.normativos.qmd -->

## 6. Acompanhamento de Programas, Ações e Projetos

Dados gerais para o acompanhamento de programas, ações e projetos.

[Acompanhe nossos Programas e Projetos](00.diversos/pagina.em.construcao.qmd)  
<!-- Endereço original: 01.gestao/06.programas.acoes.projetos.qmd -->

## 7. Estatísticas e Dados Abertos

Espaço dedicado a estatísticas, reunindo dados abertos e Relatórios Estatísticos.

[Acesse Estatísticas e Dados Abertos](00.diversos/pagina.em.construcao.qmd)  
<!-- Endereço original: 01.gestao/07.estatisticas.dados.abertos.qmd -->

## 8. Acompanhamento de Procedimentos e Processos Administrativos

Mecanismos para o acompanhamento dos procedimentos e processos administrativos.

[Monitore Procedimentos e Processos](00.diversos/pagina.em.construcao.qmd)  
<!-- Endereço original: 01.gestao/08.acompanhamento.procedimentos.qmd -->