# Auditoria e Prestação de Contas

O Tribunal Regional Eleitoral de Roraima (TRERR) assegura a transparência e responsabilidade na apresentação de suas contas e na condução de suas auditorias. Veja abaixo as informações pertinentes a esta seção:

## Informações Disponibilizadas

### 73. Prestações de Contas do Ano Anterior
Para conhecer o detalhamento da gestão financeira e orçamentária do TRERR, [acesse as prestações de contas do ano anterior](00.diversos/pagina.em.construcao.qmd).

### 74. Relatório Anual de Atividades
[Acesse o Relatório Anual de Atividades](00.diversos/pagina.em.construcao.qmd) para ter uma visão completa sobre as operações e realizações do TRERR ao longo do último ano.

### 75. Certificado de Auditoria e Parecer do Órgão de Controle Interno
[Acesse o Certificado de Auditoria e o parecer emitido pelo Órgão de Controle Interno](00.diversos/pagina.em.construcao.qmd), que avalia a conformidade das operações do tribunal com as normativas vigentes. Para mais informações.

### 76. Decisão Quanto à Regularidade das Contas pelo Órgão de Controle Externo
Para visualizar a decisão sobre a [regularidade das contas do TRERR](00.diversos/pagina.em.construcao.qmd), conforme avaliado pelo Órgão de Controle Externo.

### 77. Plano Anual de Auditoria (PAA)
[Acesso o Plano Anual de Auditoria (PAA)](00.diversos/pagina.em.construcao.qmd) para conhecer os planos e objetivos das auditorias internas a serem realizadas pelo TRERR.

### 78. Plano Anual de Capacitação de Auditoria (PAC-Aud)
[Acesse o Plano Anual de Capacitação de Auditoria (PAC-Aud)](00.diversos/pagina.em.construcao.qmd) para saber das iniciativas de capacitação para a equipe de auditoria, visando aprimorar as práticas de auditoria interna.