# Sustentabilidade e Acessibilidade

O Tribunal Regional Eleitoral de Roraima (TRERR) está comprometido com a promoção da sustentabilidade e a garantia de acessibilidade em todas as suas atividades e serviços oferecidos ao público. Confira as iniciativas e informações relacionadas:

## Sustentabilidade

- **79. Plano de Logística Sustentável (PLS)**: [Consulte aqui](00.diversos/pagina.em.construcao.qmd)
- **80. Plano de Ação do PLS**: [Consulte aqui](00.diversos/pagina.em.construcao.qmd)
- **81. Relatório Anual de Desempenho do PLS**: [Consulte aqui](00.diversos/pagina.em.construcao.qmd)
- **82. Comissão Gestora do PLS**: [Consulte aqui](00.diversos/pagina.em.construcao.qmd)

## Acessibilidade

- **83. Uso de Intérprete de Linguagem Brasileira de Sinais em Manifestações Públicas**: [Consulte aqui](00.diversos/pagina.em.construcao.qmd)
- **84. Uso de Legenda em Manifestações Públicas**: [Consulte aqui](00.diversos/pagina.em.construcao.qmd)
- **85. Uso de Audiodescrição em Manifestações Públicas**: [Consulte aqui](00.diversos/pagina.em.construcao.qmd)
- **86. Acesso ao Conteúdo para Pessoas com Deficiência**: [Consulte aqui](00.diversos/pagina.em.construcao.qmd)