project:
  type: website
  execute-dir: project
  render: 
    - index.qmd
    - pagina/*.qmd

website:
  title: "Portal da Transparência"
  navbar:
    right:
      - href: index.qmd
        text: Início
      - href: pagina/sobre.qmd
        text: Sobre
      - href: pagina/monitoramento.qmd
        text: Monitoramento
      - text: Seções
        menu: 
          - href: pagina/pagina.em.construcao.qmd #06.orcamento.qmd
            text: 06. Gestão Orçamentária
          - href: pagina/7.0.licitacoes.contratos.qmd
            text: 07. Licitações, Contratos e Instrumentos de Cooperação

format:
  html:
    theme: cosmo
    css: configuracao/styles.css
    toc: true
    
execute:
  freeze: true
  echo: false
  eval: true
  