---
title: "Sobre o TRERR"
---

## Quem Somos

O Tribunal Regional Eleitoral de Roraima (TRERR) é uma instituição chave na estrutura da Justiça Eleitoral do Brasil, responsável por garantir a execução de eleições limpas, justas e livres no estado de Roraima. Como parte do sistema judiciário brasileiro, o TRERR opera sob a supervisão do Tribunal Superior Eleitoral (TSE), assegurando que o processo eleitoral, desde o registro de eleitores até a contagem dos votos, seja conduzido com integridade, transparência e eficiência.

## Nossa Missão

Nossa missão é fortalecer a democracia no Brasil por meio da garantia de um processo eleitoral justo, transparente e acessível, promovendo a participação cidadã e assegurando que cada voto seja contado.

## Visão

Ser reconhecido como uma instituição de excelência na administração eleitoral, inovadora e de confiança, comprometida com a promoção da ética, da transparência e da responsabilidade no serviço público.

## Valores

-   **Integridade**: Agimos com honestidade e forte senso de justiça, em todas as nossas ações.
-   **Transparência**: Comprometemo-nos com a clareza e a abertura em nossas operações, promovendo o acesso à informação.
-   **Eficiência**: Buscamos a excelência na gestão dos recursos e nos processos eleitorais, otimizando resultados e garantindo a confiabilidade do voto.
-   **Cidadania**: Incentivamos a participação ativa dos cidadãos no processo democrático, fortalecendo o tecido social.
-   **Inovação**: Adotamos tecnologias e práticas inovadoras para melhorar continuamente o processo eleitoral.

## Como Trabalhamos

O TRERR está empenhado em conduzir eleições com a mais alta integridade. Isso inclui o registro de eleitores, a gestão de candidaturas, a organização do processo de votação, a contagem de votos e a certificação dos resultados eleitorais. Utilizamos tecnologia de ponta, como urnas eletrônicas, para assegurar que o processo eleitoral seja eficiente, seguro e acessível a todos os eleitores.

## Compromisso com a Comunidade

Estamos dedicados a servir a comunidade de Roraima, trabalhando incansavelmente para garantir que todos os cidadãos possam exercer seu direito de voto. Além disso, promovemos iniciativas de educação cívica e eleitoral para fortalecer a participação cidadã e a consciência política.

## Contato

Para mais informações sobre o TRERR, nossas funções e serviços, entre em contato conosco através de nosso [sítio oficial](www.tre-rr.jus.br).
